### ISSUE TITLE
cannot unmarshal !!map into string 

### ISSUE THREAD

**Issue by kumarganesh2814** [s-matyukevich/concourse-mysql-deployment#1]
Hi Sergey,

We are getting below error always while running concourse pipeline:

```
yaml: unmarshal errors:
  line 22: cannot unmarshal !!map into string
```
Pipeline is as : 
```
groups: []
resources:
- name: stemcell-version
  type: concourse-version-resource
  source: {}
- name: daily
  type: time
  source:
    interval: 24h
- name: proxy-version
  type: concourse-version-resource
  source: {}
- name: telegraf-agent-version
  type: concourse-version-resource
  source: {}
- name: mysql-version
  type: concourse-version-resource
  source: {}
- name: mysql-release-version
  type: concourse-version-resource
  source: {}
- name: concourse-mysql-deployment
  type: git
  source:
    private_key: ((git_private_key))
    uri: git@gitlab.eng.vmware.com:cpe-dri-pcf/concourse-mysql-deployment.git
resource_types:
- name: concourse-version-resource
  type: docker-image
  source:
    repository: meteogroup/concourse-version-resource
    tag: latest
jobs:
- name: deploy
  plan:
  - aggregate:
    - get: mysql-release-version
      passed:
      - build-mysql-release
      trigger: true
    - get: telegraf-agent-version
      passed:
      - build-telegraf-agent-release
      trigger: true
    - get: proxy-version
      passed:
      - upload-proxy-release
      trigger: true
    - get: stemcell-version
      passed:
      - upload-stemcell
      trigger: true
    - get: concourse-mysql-deployment
  - task: deploy
    config:
      platform: linux
      image_resource:
        type: docker-image
        source:
          repository: smatyukevich/docker-cfbosh
          tag: latest
      params:
        BACKUP_IP_DC1: 10.165.30.6
        BOSH_CA_CERT: ((bosh_ca_cert))
        BOSH_CLIENT: ((bosh_client))
        BOSH_CLIENT_SECRET: ((bosh_client_secret))
        BOSH_ENVIRONMENT: ((bosh_environment))
        BROKER_IP_DC1: 10.165.30.5
        BROKER_IP_DC2: 10.126.161.5
        CF_ADMIN_PASSWORD_DC1: ((cf_admin_password_dc1))
        CF_ADMIN_PASSWORD_DC2: ((cf_admin_password_dc2))
        CF_API_URL_DC1: https://api.us22-2-pcf1-system.oc.vmware.com
        CF_API_URL_DC2: https://api.us07-5-pcf1-system.oc.vmware.com
        CF_SKIP_SSL_VALIDATION_DC1: "true"
        CF_SKIP_SSL_VALIDATION_DC2: "true"
        CONCOURSE_TEAM: galera-admin-v2
        FRIENDLY_HOSTNAME: mysql-proxy
        MYSQL_IPS_DC1: '[10.165.30.2,10.165.30.3]'
        MYSQL_IPS_DC2: '[10.126.161.2,10.126.161.3]'
        PROXY_IP_DC1: 10.165.30.4
        PROXY_IP_DC2: 10.126.161.4
        VAULT_ADDR: https://us07-1-cc2.oc.vmware.com:8200
        VAULT_TOKEN: ((vault_token))
        WAVEFRONT_TOKEN: ((wavefront_token))
        WAVEFRONT_URL: https://try.wavefront.com/api
      run:
        path: concourse-mysql-deployment/ci/tasks/deploy-mysql.sh
      inputs:
      - name: concourse-mysql-deployment
        path: ""
  - put: mysql-version
- name: register-broker-dc1
  plan:
  - aggregate:
    - get: mysql-version
      passed:
      - deploy
      trigger: true
    - get: concourse-mysql-deployment
  - task: register-broker
    config:
      platform: linux
      image_resource:
        type: docker-image
        source:
          repository: smatyukevich/docker-cfbosh
          tag: latest
      params:
        BOSH_CA_CERT: ((bosh_ca_cert))
        BOSH_CLIENT: ((bosh_client))
        BOSH_CLIENT_SECRET: ((bosh_client_secret))
        BOSH_ENVIRONMENT: ((bosh_environment))
        BOSH_ERRAND: broker-registrar-vm-dc1
      run:
        path: concourse-mysql-deployment/ci/tasks/run-errand.sh
      inputs:
      - name: concourse-mysql-deployment
        path: ""
- name: register-broker-dc2
  plan:
  - aggregate:
    - get: mysql-version
      passed:
      - register-broker-dc1
      trigger: true
    - get: concourse-mysql-deployment
  - task: register-broker
    config:
      platform: linux
      image_resource:
        type: docker-image
        source:
          repository: smatyukevich/docker-cfbosh
          tag: latest
      params:
        BOSH_CA_CERT: ((bosh_ca_cert))
        BOSH_CLIENT: ((bosh_client))
        BOSH_CLIENT_SECRET: ((bosh_client_secret))
        BOSH_ENVIRONMENT: ((bosh_environment))
        BOSH_ERRAND: broker-registrar-vm-dc2
      run:
        path: concourse-mysql-deployment/ci/tasks/run-errand.sh
      inputs:
      - name: concourse-mysql-deployment
        path: ""
- name: backup
  plan:
  - aggregate:
    - get: concourse-mysql-deployment
    - get: daily
      trigger: true
  - task: backup
    config:
      platform: linux
      image_resource:
        type: docker-image
        source:
          repository: smatyukevich/docker-cfbosh
          tag: latest
      params:
        BOSH_CA_CERT: ((bosh_ca_cert))
        BOSH_CLIENT: ((bosh_client))
        BOSH_CLIENT_SECRET: ((bosh_client_secret))
        BOSH_ENVIRONMENT: ((bosh_environment))
        BOSH_ERRAND: broker-registrar-vm-dc2
      run:
        path: concourse-mysql-deployment/ci/tasks/backup.sh
      inputs:
      - name: concourse-mysql-deployment
        path: ""
- name: build-mysql-release
  plan:
  - aggregate:
    - get: concourse-mysql-deployment
  - task: build-mysql-release
    config:
      platform: linux
      image_resource:
        type: docker-image
        source:
          repository: smatyukevich/docker-cfbosh
          tag: latest
      params:
        BOSH_CA_CERT: ((bosh_ca_cert))
        BOSH_CLIENT: ((bosh_client))
        BOSH_CLIENT_SECRET: ((bosh_client_secret))
        BOSH_ENVIRONMENT: ((bosh_environment))
        CF_MYSQL_BROKER_URL: https://github.com/cloudfoundry/cf-mysql-broker.git
        CF_MYSQL_RELEASE_TAG: v36.16.0
        CF_MYSQL_RELEASE_URL: https://github.com/cloudfoundry/cf-mysql-release.git
      run:
        path: concourse-mysql-deployment/ci/tasks/build-mysql-release.sh
      inputs:
      - name: concourse-mysql-deployment
        path: ""
  - put: mysql-release-version
- name: build-telegraf-agent-release
  plan:
  - aggregate:
    - get: concourse-mysql-deployment
  - task: build-telegraf-agent-release
    config:
      platform: linux
      image_resource:
        type: docker-image
        source:
          repository: smatyukevich/docker-cfbosh
          tag: latest
      params:
        BOSH_CA_CERT: ((bosh_ca_cert))
        BOSH_CLIENT: ((bosh_client))
        BOSH_CLIENT_SECRET: ((bosh_client_secret))
        BOSH_ENVIRONMENT: ((bosh_environment))
        TELEGRAF_AGENT_RELEASE_URL: https://github.com/s-matyukevich/telegraf-agent-bosh-release.git
      run:
        path: concourse-mysql-deployment/ci/tasks/build-telegraf-agent-release.sh
      inputs:
      - name: concourse-mysql-deployment
        path: ""
  - put: telegraf-agent-version
- name: upload-proxy-release
  plan:
  - aggregate:
    - get: concourse-mysql-deployment
  - task: upload-proxy-release
    config:
      platform: linux
      image_resource:
        type: docker-image
        source:
          repository: smatyukevich/docker-cfbosh
          tag: latest
      params:
        BOSH_CA_CERT: ((bosh_ca_cert))
        BOSH_CLIENT: ((bosh_client))
        BOSH_CLIENT_SECRET: ((bosh_client_secret))
        BOSH_ENVIRONMENT: ((bosh_environment))
        WAVEFRONT_PROXY_RELEASE_URL: https://github.com/s-matyukevich/cloud-foundry-release/releases/download/v0.0.1/wavefront-proxy-1.tgz
      run:
        path: concourse-mysql-deployment/ci/tasks/upload-proxy-release.sh
      inputs:
      - name: concourse-mysql-deployment
        path: ""
  - put: proxy-version
- name: upload-stemcell
  plan:
  - aggregate:
    - get: concourse-mysql-deployment
  - task: upload-stemcell
    config:
      platform: linux
      image_resource:
        type: docker-image
        source:
          repository: smatyukevich/docker-cfbosh
          tag: latest
      params:
        BOSH_CA_CERT: ((bosh_ca_cert))
        BOSH_CLIENT: ((bosh_client))
        BOSH_CLIENT_SECRET: ((bosh_client_secret))
        BOSH_ENVIRONMENT: ((bosh_environment))
        STEMCELL_URL: https://bosh.io/d/stemcells/bosh-vsphere-esxi-ubuntu-trusty-go_agent?v=
        STEMCELL_VERSION: "3586.52"
      run:
        path: concourse-mysql-deployment/ci/tasks/upload-stemcell.sh
      inputs:
      - name: concourse-mysql-deployment
        path: ""
  - put: stemcell-version
```
Can you please suggest what is we are missing here.

Best Regards
GAnesh Kumar
